# Generated by Django 5.0.6 on 2024-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('activate', models.BooleanField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status_product', models.BooleanField()),
            ],
            options={
                'db_table': 'cart_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='images/image_categories/')),
                ('image_banner', models.ImageField(upload_to='images/banner/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id_coupon', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_value', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('discount', 'Discount'), ('discount_product', 'Discount Product')], max_length=20)),
                ('time_used', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('activate', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name_customer', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportProducts',
            fields=[
                ('id_imp', models.AutoField(primary_key=True, serialize=False)),
                ('import_quantity', models.IntegerField()),
                ('import_price', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('import_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('import_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'import_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPages',
            fields=[
                ('id_landing_pages', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/landing_pages/')),
                ('activate', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'landing_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_description', models.TextField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.BooleanField()),
                ('order_status', models.CharField(choices=[('waiting for confirmation', 'Waiting for confirmation'), ('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('delivered successfully', 'Delivered successfully')], max_length=50)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCoupons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('sku', models.CharField(db_column='SKU', max_length=50, unique=True)),
                ('export_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.TextField(max_length=1000)),
                ('image_product', models.ImageField(upload_to='images/image_products/')),
                ('brand', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=255)),
                ('activate', models.BooleanField()),
                ('status', models.CharField(choices=[('Còn hàng', 'Còn hàng'), ('Hết hàng', 'Hết hàng')], max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('review_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='images/image_user/')),
                ('account_type', models.CharField(choices=[('employee', 'employee'), ('customer', 'customer')], max_length=50)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wishlists',
                'managed': False,
            },
        ),
    ]
